esphome:
  name: sensehajo
  friendly_name: SenseHaJo
  project:
    name: "eHaJo.SenseHaJo"
    version: "0.1.0"
  on_boot:
    then:
      - delay: 2s  # Zeige das Logo für 2 Sekunden
      - lambda: |-
          id(boot_finished) = true;
      - script.execute: script_all_off

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: INFO

i2c:
  sda: GPIO32
  scl: GPIO14
  frequency: 200kHz

# Bildressource definieren
image:
  - file: "ehajo_bw.xbm"
    id: ehajo_bw
    type: BINARY

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    id: oled_display
    update_interval: 1s
    lambda: |-
      if (id(boot_finished)) {
        it.printf(20, 0, id(font_large), "SenseHaJo");
        it.printf(15, 16, id(font_small), "Boiler: %.1f°C", id(sensor_boilertemp).state);
        switch(id(_sensehajo_state)) {
          case 0: it.print(52, 48, id(font_small), "AUS"); break;
          case 10: it.print(47, 48, id(font_small), "STBY"); break;
          case 15: it.print(42, 48, id(font_small), "READY"); break;
          case 20: it.print(42, 48, id(font_small), "Kochen"); break;
          case 40: it.print(42, 48, id(font_small), "Spülen"); break;
          case 100: it.print(42, 48, id(font_small), "Error"); break;
        }
      }
      else {
        it.image(0, 0, id(ehajo_bw));
      }

font:
  - file: "courbd.ttf"
    id: font_large
    size: 16
  - file: "courbd.ttf"
    id: font_small
    size: 12

api:
  encryption:
    key: !secret api-key

ota:
  - platform: esphome
    password: !secret ota-pw

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Sensehajo Fallback Hotspot"
    password: !secret fallback-pw

captive_portal:

globals:
  - id: _sensehajo_state
    type: int
    restore_value: no
    initial_value: '0'
    #  0 ... AUS
    # 10 ... STBY
    # 15 ... READY
    # 20 ... Kaffee kochen
    # 25 ... Aufheizen - Kaffee - Aus
    # 40 ... Spülen
    # 100 ... error
  - id: boot_finished  # Neue Variable für Boot-Status
    type: bool
    restore_value: no
    initial_value: 'false'

light:
  - platform: neopixelbus
    id: "sensehajo_ws2812"
    type: GRB
    variant: WS2812
    pin: GPIO18
    num_leds: 3
  - platform: partition
    id: "sensehajo_LED1"
    default_transition_length: 0s
    segments:
      - id: sensehajo_ws2812
        from: 0
        to: 0
    effects:
      - random:
          name: "Kaffeekochen"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Kaffeewarten"
          transition_length: 0.3s
          update_interval: 0.3s
          min_brightness: 20%
          max_brightness: 50%
  - platform: partition
    id: "sensehajo_LED2"
    default_transition_length: 0s
    segments:
      - id: sensehajo_ws2812
        from: 1
        to: 1
    effects:
      - random:
          name: "Spuelen"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Fast Pulse"
          transition_length: 0.3s
          update_interval: 0.3s
          min_brightness: 20%
          max_brightness: 50%
  - platform: partition
    id: "sensehajo_LED3"
    default_transition_length: 0s
    segments:
      - id: sensehajo_ws2812
        from: 2
        to: 2
    effects:
      - random:
          name: "Kaffeekochen"
          transition_length: 0.5s
          update_interval: 0.5s
      - pulse:
          name: "Kaffeewarten"
          transition_length: 0.3s
          update_interval: 0.3s
          min_brightness: 20%
          max_brightness: 50%

number:
  - platform: template
    id: sensehajo_bruehzeit
    name: "Brühzeit"
    icon: mdi:timer-cog-outline
    min_value: 1
    max_value: 30
    step: 1
    restore_value: true
    optimistic: true
    unit_of_measurement: "s"
  - platform: template
    id: sensehajo_kaffeetemp
    name: "Brühtemperatur"
    icon: mdi:water-thermometer
    min_value: 50
    max_value: 90
    restore_value: true
    step: 1
    optimistic: true
    unit_of_measurement: "°C"

button:
  - platform: template
    name: "SenseHaJo einschalten"
    id: button_turnON
    icon: "mdi:power"
    on_press:
      - script.execute: script_power_on
  - platform: template
    name: "1 Tasse Kaffee"
    id: button_1coffee
    icon: "mdi:coffee"
    on_press:
      - script.execute:
          id: script_prepare_coffee
          cups: 1
  - platform: template
    name: "2 Tassen Kaffee"
    id: button_2coffee
    icon: "mdi:coffee"
    on_press:
      - script.execute:
          id: script_prepare_coffee
          cups: 2

binary_sensor:
  - platform: gpio
    id: "sensehajo_Taste1"
    pin:
      number: GPIO23
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_click:
      - min_length: 50ms
        max_length: 350ms
        then:
          - script.execute:
              id: script_prepare_coffee
              cups: 2
  - platform: gpio
    id: "sensehajo_Taste2"
    pin:
      number: GPIO26
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_click:
      - min_length: 50ms
        max_length: 350ms
        then:
          - script.execute: script_power_on
      - min_length: 2s
        max_length: 10s
        then:
          - script.execute: script_spuelen
  - platform: gpio
    id: "sensehajo_Taste3"
    pin:
      number: GPIO27
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_click:
      - min_length: 50ms
        max_length: 350ms
        then:
          - script.execute:
              id: script_prepare_coffee
              cups: 1
  - platform: gpio
    id: "sensehajo_Hallsensor"
    pin:
      number: GPIO21
  - platform: gpio
    id: "sensehajo_Reed2"
    name: "Reed 2"
    pin:
      number: GPIO34
      inverted: true
    on_press:
      - lambda: |-
          if (id(_sensehajo_state) == 100) {
            id(_sensehajo_state) = 10;
            id(regulate_temperature).execute();
            auto call2 = id(sensehajo_LED2).turn_on();
            call2.set_brightness(0.5);
            call2.set_rgb(0,0,1);
            call2.set_effect("None");
            call2.perform();
          }
    on_release:
      - lambda: |-
          if(id(_sensehajo_state) == 20) {
            id(script_coffeetime).stop();
            auto call = id(sensehajo_LED2).turn_on();
            call.set_brightness(0.5);
            call.set_rgb(0,1,0);
            call.set_effect("Fast Pulse");
            call.perform();
            id(gpio_pumpe).turn_off();
            id(sensehajo_LED3).turn_off().perform();
            id(sensehajo_LED1).turn_off().perform();
          } else if(id(_sensehajo_state) == 40) {
            id(script_spuelen).stop();
            id(script_all_off).execute();
          } else if(id(_sensehajo_state) != 0) {
            id(_sensehajo_state) = 100;
            id(script_error).execute();
          }

switch:
  - platform: gpio
    pin: 5
    id: gpio_pumpe
    icon: mdi:water-pump
    restore_mode: ALWAYS_OFF
  - platform: gpio
    id: gpio_heizung
    pin: 19
    icon: mdi:thermometer-water
    restore_mode: ALWAYS_OFF

sensor:
  - platform: template
    id: template_boilertemp
    name: "Boilertemperatur"
    icon: mdi:water-thermometer
    update_interval: 1s
    lambda: |-
        return id(sensor_boilertemp).state;
    unit_of_measurement: "°C"
    device_class: temperature
  - platform: template
    id: template_state
    name: "SenseHaJo State"
    icon: "mdi:state-machine"
    lambda: |-
        return id(_sensehajo_state);
    update_interval: 1s
  - platform: ntc
    id: sensor_boilertemp
    icon: mdi:water-thermometer
    sensor: tempsense_resistance
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
  - platform: resistance
    id: tempsense_resistance
    sensor: tempsense_source
    configuration: DOWNSTREAM
    resistor: 2.7kOhm
  - platform: adc
    id: tempsense_source
    attenuation: 12dB
    update_interval: 0.1s
    pin: GPIO36
    raw: true
    filters:
      - multiply: 0.00095238

script:
  - id: script_error
    then:
      - lambda: |-
          id(_sensehajo_state) = 100;
      - light.turn_on:
          id: sensehajo_ws2812
          brightness: 50%
          red: 100%
          green: 0%
          blue: 0%
          effect: "Fast Pulse"
      - delay: 30s
      - script.execute: script_all_off

  - id: script_power_on
    then:
      - lambda: |-
          if (id(sensehajo_Reed2).state) {
            id(script_timout).execute();
            auto call = id(sensehajo_LED2).turn_on();
            call.set_brightness(0.5);
            call.set_rgb(1,0,0);
            call.set_effect("None");
            call.perform();
            if (id(_sensehajo_state) == 0) {
                id(_sensehajo_state) = 10;
                id(regulate_temperature).execute();
            } else {
                id(_sensehajo_state) = 0;
                id(script_all_off).execute();
            }
          } else {
            auto call2 = id(sensehajo_LED2).turn_on();
            call2.set_brightness(0.5);
            call2.set_rgb(0.5,0.5,1);
            call2.set_effect("Fast Pulse");
            call2.perform();
            if (id(_sensehajo_state) == 0) {
                id(_sensehajo_state) = 100;
                id(script_error).execute();
            } else {
                id(_sensehajo_state) = 0;
                id(script_all_off).execute();
            }
          }

  - id: script_all_off
    then:
      - lambda: |-
          id(script_spuelen).stop();
          id(script_coffeetime).stop();
          id(script_power_on).stop();
          id(regulate_temperature).stop();
          id(_sensehajo_state) = 0;
      - switch.turn_off: gpio_heizung
      - switch.turn_off: gpio_pumpe
      - delay: 500ms
      - light.turn_off: sensehajo_LED1
      - light.turn_off: sensehajo_LED2
      - light.turn_off: sensehajo_LED3

  - id: script_prepare_coffee
    parameters:
      cups: int
    then:
      - if:
          condition:
            lambda: |-
                return id(_sensehajo_state) == 0;
          then:
            - script.execute: script_power_on
            - lambda: |-
                auto call = (cups == 1) ? id(sensehajo_LED3).turn_on() : id(sensehajo_LED1).turn_on();
                call.set_brightness(0.5);
                call.set_rgb(0,0,1);
                call.set_effect("Kaffeewarten");
                call.perform();
            - wait_until:
                condition:
                  lambda: |-
                      return id(_sensehajo_state) == 15;
                timeout: 1min
      - script.execute:
          id: script_coffeetime
          cups: !lambda |-
              return cups;

  - id: script_coffeetime
    parameters:
      cups: int
    then:
      - script.execute: script_timout
      - lambda: |-
          if((id(_sensehajo_state) != 15) || !id(sensehajo_Reed2).state) {
            id(script_coffeetime).stop();
            id(script_error).execute();
          }
      - lambda: |-
          id(_sensehajo_state) = 20;
          if(cups == 1) {
            auto call = id(sensehajo_LED3).turn_on();
            call.set_brightness(0.5);
            call.set_rgb(0,1,0);
            call.set_effect("Kaffeekochen");
            call.perform();
          } else {
            auto call = id(sensehajo_LED1).turn_on();
            call.set_brightness(0.5);
            call.set_rgb(0,1,0);
            call.set_effect("Kaffeekochen");
            call.perform();
          }
      - switch.turn_on: gpio_pumpe
      - delay: !lambda |-
          return cups * id(sensehajo_bruehzeit).state * 1000;
      - switch.turn_off: gpio_pumpe
      - light.turn_off: sensehajo_LED1
      - light.turn_off: sensehajo_LED3
      - lambda: |-
          id(_sensehajo_state) = 15;
      - script.execute: script_timout

  - id: script_spuelen
    then:
      - lambda: |-
          if ((id(_sensehajo_state) == 0 || id(_sensehajo_state) == 15) && id(sensehajo_Reed2).state) {
            auto call = id(sensehajo_LED2).turn_on();
            call.set_brightness(0.5);
            call.set_rgb(0.5,0.5,1);
            call.set_effect("Spuelen");
            call.perform();
            id(gpio_pumpe).turn_on();
            id(_sensehajo_state) = 40;
          } else {
            id(script_spuelen).stop();
            id(script_error).execute();
          }
      - delay: 60s
      - lambda: |-
          id(_sensehajo_state) = 0;
      - script.execute: script_all_off

  - id: script_timout
    mode: restart
    then:
      - delay: 5min
      - script.execute: script_all_off

  # Benutzerdefinierte Temperaturregelung
  - id: regulate_temperature
    mode: single  # Läuft nur einmal, bis gestoppt
    then:
      - while:
          condition:
            lambda: 'return id(_sensehajo_state) == 10 || id(_sensehajo_state) == 15;'
          then:
            - lambda: |-
                float current_temp = id(sensor_boilertemp).state;
                float target_temp = id(sensehajo_kaffeetemp).state;
                float error = target_temp - current_temp;
                // Einfacher P-Regler
                if (error > 0.5) {  // Heizen, wenn mehr als 0.5°C unter Sollwert
                  id(gpio_heizung).turn_on();
                } else if (error <= 0) {  // Ausschalten, wenn Sollwert erreicht
                  id(gpio_heizung).turn_off();
                  if (id(_sensehajo_state) == 10) id(_sensehajo_state) = 15;  // READY
                }
            - delay: 100ms  # Schnelle Regelung alle 100ms